# -*- coding: utf-8 -*-
"""problema 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ArsDSRun62dqY39WfJQMOe1StO_fQ-H5
"""

# -*- coding: utf-8 -*-
"""problema 1 .ipynb
Automatically generated by Colab.
"""

# Definición de la matriz inicial con 5 filas (ID Cliente, Duración, Clics)
matriz_sesiones = [
    [101, 190, 10],
    [102, 50, 5],
    [103, 120, 6],
    [104, 200, 2],
    [105, 180, 8]
] # FALTABA ESTE CORCHETE

# Módulo (función) para evaluar el nivel de compromiso
def evaluar_compromiso(matriz):
    # NOTA LOS ESPACIOS A LA IZQUIERDA AQUÍ ABAJO
    print(f"{'ID Cliente':<15} {'Clasificación'}")
    print("-" * 30)

    # Recorro cada fila de la matriz
    for sesion in matriz:
        id_cliente = sesion[0]
        duracion = sesion[1]
        clics = sesion[2]

        # Lógica de negocio
        if duracion > 180 and clics > 8:
            clasificacion = "Alto"
        elif duracion < 60 or clics < 3:
            clasificacion = "Bajo"
        else:
            clasificacion = "Medio"

        # Genero la salida esperada
        print(f"{id_cliente:<15} {clasificacion}")

# Llamado a la función
evaluar_compromiso(matriz_sesiones)